export const ENTITY_STYLES = {
  Customer: { fill: "#ff6e75", stroke: "#ff9096", text: "#7f2d38" },
  Address: { fill: "#ff9b80", stroke: "#ffb49e", text: "#7a4333" },
  Product: { fill: "#8fb7ff", stroke: "#c2d8ff", text: "#2c518f" },
  Plant: { fill: "#7ed7b7", stroke: "#c3efdf", text: "#1f6d54" },
  Order: { fill: "#3f82ff", stroke: "#94bcff", text: "#17498f" },
  SalesOrderItem: { fill: "#47c7c4", stroke: "#baf1ee", text: "#155b5e" },
  SalesOrderScheduleLine: { fill: "#f0b96d", stroke: "#f7d9ae", text: "#7d5320" },
  Delivery: { fill: "#5fa8ff", stroke: "#b7d5ff", text: "#1f5a94" },
  Invoice: { fill: "#7d9cff", stroke: "#c7d7ff", text: "#334b8c" },
  Payment: { fill: "#a3c4ff", stroke: "#dce9ff", text: "#3f628f" },
  JournalEntryItem: { fill: "#c8b5ff", stroke: "#e4d9ff", text: "#5a4791" },
};

export const ENTITY_FIELD_PRIORITY = {
  Customer: [
    "customer_id",
    "business_partner_id",
    "full_name",
    "business_partner_category",
    "business_partner_grouping",
    "last_change_date",
    "is_blocked",
    "is_marked_for_archiving",
  ],
  Address: [
    "address_id",
    "street_name",
    "city_name",
    "region",
    "country",
    "postal_code",
    "validity_end_date",
  ],
  Product: [
    "product_id",
    "product_description",
    "product_type",
    "product_group",
    "base_unit",
    "gross_weight",
    "net_weight",
    "weight_unit",
  ],
  Plant: [
    "plant_id",
    "plant_name",
    "valuation_area",
    "sales_organization",
    "distribution_channel",
    "division",
    "address_id",
  ],
  Order: [
    "order_id",
    "customer_id",
    "sales_organization",
    "distribution_channel",
    "transaction_currency",
    "total_net_amount",
    "requested_delivery_date",
    "overall_delivery_status",
  ],
  SalesOrderItem: [
    "sales_order_item_id",
    "order_id",
    "order_item_id",
    "product_id",
    "requested_quantity",
    "requested_quantity_unit",
    "production_plant",
    "storage_location",
  ],
  SalesOrderScheduleLine: [
    "schedule_line_id",
    "sales_order_item_id",
    "order_id",
    "order_item_id",
    "schedule_line",
    "confirmed_delivery_date",
    "confirmed_order_quantity",
    "order_quantity_unit",
  ],
  Delivery: [
    "delivery_id",
    "actual_goods_movement_date",
    "shipping_point",
    "delivery_priority",
    "overall_goods_movement_status",
    "overall_picking_status",
  ],
  Invoice: [
    "invoice_id",
    "customer_id",
    "billing_document_type",
    "billing_document_date",
    "transaction_currency",
    "total_net_amount",
    "accounting_document",
    "cancelled_invoice_id",
  ],
  Payment: [
    "payment_document",
    "company_code",
    "fiscal_year",
    "customer_id",
    "transaction_currency",
    "amount_in_transaction_currency",
    "clearing_date",
    "posting_date",
    "applied_invoice_count",
  ],
  JournalEntryItem: [
    "journal_entry_item_id",
    "invoice_id",
    "customer_id",
    "accounting_document",
    "accounting_document_item",
    "gl_account",
    "transaction_currency",
    "amount_in_transaction_currency",
    "clearing_payment_id",
    "clearing_date",
  ],
};

export const CLUSTER_LAYOUT = {
  Address: { x: -1040, y: -300, angle: 4.0, spread: 14 },
  Customer: { x: -760, y: -60, angle: 3.0, spread: 18 },
  Order: { x: -330, y: 120, angle: 2.4, spread: 16 },
  SalesOrderItem: { x: -60, y: 250, angle: 1.95, spread: 14 },
  SalesOrderScheduleLine: { x: 260, y: 240, angle: 1.45, spread: 13 },
  Delivery: { x: 40, y: -180, angle: 4.9, spread: 15 },
  Invoice: { x: 360, y: -10, angle: 5.8, spread: 17 },
  Payment: { x: 730, y: 250, angle: 0.9, spread: 15 },
  JournalEntryItem: { x: 980, y: -70, angle: 0.3, spread: 16 },
  Product: { x: 140, y: 330, angle: 1.7, spread: 14 },
  Plant: { x: 520, y: 360, angle: 1.15, spread: 13 },
};
